kind: ConfigMap
apiVersion: v1
metadata:
  name: minergate
data:
  CURRENCY: xmr
  USER: sonidos.de.aquel.dia@gmail.com

---

apiVersion: v1
kind: Pod
metadata:
  name: minergate
spec:
  containers:
  - name: minergate
    image: hichtakk/minergate-cli:latest
    envFrom:
    - configMapRef:
        name: minergate

